import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Root } from "@/components/Root/Root";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ru">
      <body>
        <Root>
          { children }
        </Root>
      </body>
    </html>
  );
}
